package com.dht.constant;

public interface RoleConstants {
    int DEFAULTSTATUS = 1;
    String UPDATEROLEREFPERMCLEAR = "UPDATEROLEREFPERMCLEAR";
    String UPDATEROLEREFPERMSUCCESS = "UPDATEROLEREFPERMSUCCESS";
    String UPDATEROLEREFPERMFAIL = "UPDATEROLEREFPERMFAIL";
}
